#spring.application.name=TentaculoMimico

#spring.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.uri=${MONGO_URI}
#spring.thymeleaf.cache=false



spring.application.name=TentaculoMimico

spring.mongodb.uri=mongodb+srv://tm_daniela:daniela@escola.fra1bg.mongodb.net/tentaculo_mimico?appName=escola
spring.thymeleaf.cache=false