spring.application.name=TentaculoMimico
spring.data.mongodb.uri=${MONGO_URI}
spring.thymeleaf.cache=false

server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= //criar um e-mail para suporte
spring.mail.password= //criar uma senha para suporte

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true