spring.application.name=TentaculoMimico
server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= tentaculomimico.dev@gmail.com
spring.mail.password= 2026-09-05_16-02_t3nt4cul0m1m1c0_dbaccesspi3

spring.mongodb.uri=${MONGO_URI}
#spring.data.mongodb.uri=${MONGO_URI}
spring.thymeleaf.cache=false
>>>>>>> 5a235a98bea048643d8bd30a62ec1ccbe6aa3b54
